import AccordionComponent from "../components/Accordion/AccordionComponent.vue";
import AccordionItem from "../components/Accordion/AccordionItem.vue";

// More on default export: https://storybook.js.org/docs/vue/writing-stories/introduction#default-export
export default {
  title: "Example/Accordion",
  components: { AccordionComponent, AccordionItem },
};

export const Primary = () => ({
  components: { AccordionComponent, AccordionItem },
  setup() {},
  template:
    '<AccordionComponent width="80vw" :centerItem="true"  ><AccordionItem heading="List Two" label="label_primary" content="content_primary" headingColor="white" bgContent="#f7f5f7" > <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!</p>    </AccordionItem> <AccordionItem heading="List Two" label="label_primary" content="content_primary" headingColor="white" bgContent="#f7f5f7" > <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!</p>    </AccordionItem></AccordionComponent >',
});

export const PrimaryDark = () => ({
  components: { AccordionComponent, AccordionItem },
  setup() {},
  template:
    '<AccordionComponent width="80vw" :centerItem="true" ><AccordionItem heading="List One" label="label_primary_dark" content="content_primary_dark"  > <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!</p>    </AccordionItem> <AccordionItem heading="List One" label="label_primary_dark" content="content_primary_dark"> <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!</p>  </AccordionItem>  </AccordionItem></AccordionComponent >',
});

export const Secondary = () => ({
  components: { AccordionComponent, AccordionItem },
  setup() {},
  template:
    '<AccordionComponent width="80vw" :centerItem="true" ><AccordionItem heading="List Two" label="label_secondary" content="content_secondary" headingColor="white" contentColor="white" bgHeading="#2e382b" borderColor="#475447" fsHeading="2vw" fsContent="1.4vw" bgContent="#f7f5f7" > <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!</p></AccordionItem><AccordionComponent width="80vw" :centerItem="true" ><AccordionItem heading="List Two" label="label_secondary" content="content_secondary" headingColor="white" contentColor="white" bgHeading="#2e382b" borderColor="#475447" fsHeading="2vw" fsContent="1.4vw" bgContent="#f7f5f7" > <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!</p>   </AccordionItem>  </AccordionItem></AccordionComponent>',
});

export const SecondaryDark = () => ({
  components: { AccordionComponent, AccordionItem },
  setup() {},
  template:
    '<AccordionComponent width="80vw" :centerItem="true" ><AccordionItem heading="List One" label="label_secondary" content="content_secondary_dark" > <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!</p>    </AccordionItem> <AccordionItem heading="List One" label="label_secondary" content="content_secondary_dark" > <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!  Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae saepe necessitatibus laboriosam architecto tempore a dicta quod sunt doloribus perspiciatis!</p>    </AccordionItem>  </AccordionItem></AccordionComponent >',
});
